- hosts: all
  become: true
  roles:
    - role: angstwad.docker_ubuntu
        - src: angstwad.docker_ubuntu

  tasks:
    - name: update ubuntu
      apt: update_cache=yes

  #  - name: install docker
  #    apt: name="docker.io" state=present

    - name: install PIP
      apt:
        name: python-pip
        state: installed

    - name: install docker using PIP
      pip:
        name: "{{ item.name }}"
        state: present
      with_items:
        - { name: docker-py }

    - name: build docker containers
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
      with_items:
        - { name: tools, tag: "tools", image: "nginx" }
        - { name: nginx, tag: "web", image: "mariadb:latest" }
        - { name: db, tag: "db", image: "ubuntu:16.04" }
